# Generated by Django 5.2.5 on 2026-02-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_membersinfo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersinfo',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
