# Generated by Django 5.2.5 on 2026-02-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetId', models.IntegerField(primary_key=True, serialize=False)),
                ('meetingdate', models.DateField()),
                ('location', models.CharField(max_length=90)),
                ('Meet_status', models.CharField(default='Active', max_length=10)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('DateEdited', models.DateField(auto_now=True)),
            ],
        ),
    ]
