# Generated by Django 5.2.5 on 2026-02-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='MeetNo',
            field=models.IntegerField(null=True),
        ),
    ]
