# Generated by Django 5.2.5 on 2026-02-22 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_meeting_meetno'),
        ('members', '0002_alter_membersinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members_attendanceTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('meetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.meeting')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membersinfo')),
            ],
        ),
    ]
