# Generated by Django 5.2.5 on 2026-02-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_members_attendancetb'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_attendancetb',
            name='Ruhusa',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='members_attendancetb',
            name='mtoaTaarifa',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
