# Generated by Django 5.2.5 on 2026-02-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_members_attendancetb_ruhusa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_attendancetb',
            name='meetId',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='members_attendancetb',
            name='memberID',
            field=models.CharField(max_length=15),
        ),
    ]
