# Generated by Django 5.2.5 on 2026-02-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_members_attendancetb_meetid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_attendancetb',
            name='status',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
